title: "Ragdoll Dreams"
description: "Питомник кошек породы рэгдолл, предлагающий здоровых, ласковых котят с чемпионскими кровными линиями."
url: "https://ragdolldreams.netlify.app"
baseurl: ""

lang: ru

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  kittens:
    output: false

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - .git
backend:
  name: git-gateway
  branch: lab4