title: "Ragdoll Dreams"
description: "Питомник кошек породы рэгдолл, предлагающий здоровых, ласковых котят с чемпионскими кровными линиями."
url: "https://sabinapopescu.github.io/tum-web-lab2"
baseurl: "/tum-web-lab2"

lang: ru

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  kittens:
    output: false

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - .git
